### ISSUE TITLE
No light when touching water

### ISSUE THREAD

**Issue by bananarceus** [bigmanmad/torchesntrinkets-1.20.1#2]
Hiii! So I've noticed the belt doesn't have dynamic lights underwater or even just touching water. 

Thanks for reading!

**Comment by bigmanmad** [comment]
make sure water sensitivity check is off and it will work
![image](https://github.com/bigmanmad/torchesntrinkets-1.20.1/assets/82972438/409d1a92-1143-41b8-97e9-b9257d1fc5b8)

**Comment by bananarceus** [comment]
Thanks!!!! Sorry for the late reply, I lost my account access xD
