### ISSUE TITLE
Water Sensitivity Check

### ISSUE THREAD

**Issue by geometryflame111** [bigmanmad/torchesntrinkets-1.20.1#5]
While testing the [Latest Version](https://modrinth.com/mod/torches-n-trinkets/version/vQc0rlkw) on Fabric 1.20.1, I noticed an irregularity. [LambDynamicLights](https://modrinth.com/mod/lambdynamiclights) treats all three trinkets as if they are sensitive to light.

The Torch Belt makes sense, it's a torch. However, lanterns can be waterlogged (and are therefore canonically waterproof). The Lantern Belt and Soul Lantern Belt should therefore not be sensitive to water.

![Image](https://github.com/user-attachments/assets/d62c3f98-409d-46cc-9d5e-6017dc7ae493)

**Comment by geometryflame111** [comment]
I figured I should mention, I already know that I can disable the water sensitivity configuration. However, items like the lantern are already treated as water insensitive by [LambDynamicLights](https://modrinth.com/mod/lambdynamiclights). I imagine it should also be possible to transfer this property to the lantern trinkets, unless there's a related issue with [Radiant Gear](https://modrinth.com/mod/radiant-gear) that prevents this.

**Comment by bigmanmad** [comment]
its likely to do with radiant gear as my mod just adds a trinket slot and a few items, the dynamic lighting is handled with radiant gear's trinket stuff and obviously dynamic lights, perhaps im wrong and if so let me know so i can fix it

**Comment by geometryflame111** [comment]
If I had to guess, I'd say you're missing some configuration files. Alternatively, there may be some kind of property you could add to the items, but I got onto the [Radiant Gear](https://modrinth.com/mod/radiant-gear) [Discord Server](https://discord.gg/JWgrdwt) and noticed a few cases where people were asking questions about it and configuration files for dynamic light mods were mentioned. Perhaps that's the solution?

I asked a question in the [Support Channel](https://discord.com/channels/500852157503766538/1269230835937185883) to check, but as of writing this haven't had an immediate response.

**Comment by geometryflame111** [comment]
Would having an example help? I found a mod called [Wearable Lanterns](https://modrinth.com/mod/wearable-lanterns).
Dug through the code a bit, I think I found the [related files](https://github.com/AbsentAbigail/WearableLantern/tree/master/src/main/resources/assets/trinketlantern/dynamiclights/item).
You just need to change a boolean value...
