### ISSUE TITLE
Wont let me equip a lantern / torch in slot

### ISSUE THREAD

**Issue by SurfaceShark** [bigmanmad/torchesntrinkets-1.20.1#7]
In just wont let me place an item in the slot, i use a bunch of mods, maybe it is cuz they conflict?? 
Please help

**Comment by GenericQuinn** [comment]
Same. Bump. 
(Playing AoF 7 1.20.1)

**Comment by bigmanmad** [comment]
the mod adds a belt item for the torch, lantern and soul lantern so perhaps that's your issue? or can you not put the belt in the slot due to a confliction?

**Comment by SurfaceShark** [comment]
> the mod adds a belt item for the torch, lantern and soul lantern so perhaps that's your issue? or can you not put the belt in the slot due to a confliction?

Yeah, i had to equip the BELT, not the torch itself, im just dumb sry xd
